### ISSUE TITLE
Resetting settings doesn't update theme dropdown

### ISSUE THREAD

**Issue by fractioneater** [twodee/twoville#24]
Clicking the "Reset settings" button updates the theme, but not the dropdown for changing the theme.

Screen recording:
[Screen recording 2023-02-06 15.28.41.webm](https://user-images.githubusercontent.com/98233032/217078277-51e59f03-db1e-432d-9a83-2c10352a78a6.webm)

**Comment by twodee** [comment]
Hmm. I had the code for this in place but it was commented out. I can't remember why. It's reinstated now.

Fixed by 9493012.
